### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by joshmoore**
A simple (largely Python2) `Dockerfile` that I used for local testing in case it's of use to anyone:

```
docker build -t db .
docker run -ti --rm db --control=... --experiment=...
```

### CODE REVIEW

**Comment by adamchainz** [comment]
Django 2 only supports Python 3 so we'd need that to merge :)

**Comment by joshmoore** [comment]
@adamchainz : I'm in Python2 land but it should be straight-forward enough to add in Python3. Would the preference be for 2 Dockerfiles (easier to use from Docker Hub) or 1 Dockerfile with args for choosing between the two?

**Comment by adamchainz** [comment]
Afraid I have no idea, I'm not really a Docker user :)

**Comment by joshmoore** [comment]
@adamchainz : fair enough :smile: I've done the simplest thing possible for Python3 users then. If anyone wants to see a Python2-capable image on Docker Hub, then another file will be needed. Otherwise, this will suffice:

```
$ docker build --build-arg IMAGE=conda/miniconda2 -t db .
```

**Comment by adamchainz** [comment]
Ok cool 👌

**Comment by joshmoore** [comment]
Closing this PR to clean up my listing. You're of course free to re-open/cherry-pick.

**Pull request closed without merging**
